services:
  db:
    image: postgres:17
    container_name: eloconnect-db
    environment:
      POSTGRES_USER: eloconnect
      POSTGRES_PASSWORD: eloconnect
      POSTGRES_DB: eloconnect
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
